### ISSUE TITLE
python-decouple missing from requirements

### ISSUE THREAD

**Issue by CupCakeArmy** [justdjango/django-react-ecommerce#1]

**Comment by liki** [comment]
Hi, could you try to run the following shell?

pip install python-decouple

Thanks,

**Comment by CupCakeArmy** [comment]
Ye, no problem then. Just wanted to point it out, we all forget some deps from time to time. Looking forward to the full tutorial 🚀

**Comment by justdjango** [comment]
Added it in the latest commit
